version: "3"

services:
  web:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017"
    volumes:
      - data:/bitnami/mongodb
    expose:
      - "27017"


volumes:
  data:
